### ISSUE TITLE
gettting the year/date for a post not working in my WP install

### ISSUE THREAD

**Issue by tonzyl** [cogdog/wp-posted-today#1]
Not sure why but the line
$post_year = date("Y", strtotime( get_the_date() )); 
in your code
gives me the current year, breaking the entire if then loop that creates the strong header per year.

When I changed it to $post_year = get_the_date('Y');
it worked as your examples suggest.

I'm on WP 5.0.3.

**Comment by cogdog** [comment]
Hmmm, and I have no idea why I wrote what looks redundant, probably lifted from another example.

Made an adjustment in the plugin, thanks. It should not be needed, but just to be sure, I am passing the ID of the post too

````
$post_year = get_the_date('Y', $posts_from_today->post->ID );
````
